name: hot_and_cold
description: A new Flutter application.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.25.4
  # Useful for translation, date formatting
  intl: ^0.16.1
  flutter_localizations:
    sdk: flutter
  # On device storage
  shared_preferences: ^0.5.6
  flutter_secure_storage: ^3.3.5
  # Animations
  flare_flutter: ^2.0.6
  # API
  http: ^0.12.2
  dio: ^3.0.10
  json_serializable: ^3.5.1
  # Access files on device
  path_provider: ^1.6.11
  path: any
  # Customize launch icon
  flutter_launcher_icons: ^0.7.3
  # State Management
  flutter_bloc: ^6.1.2
  # Use to compare object
  equatable: ^1.2.6
  permission_handler: ^5.1.0+2
  geolocator: ^6.2.0
  jpec_base:
    git:
      url: https://github.com/Jpec57/jpec_base.git
      ref: master
  ## PROJECT
  flutter_compass: '^0.4.3'
  cupertino_icons: ^1.0.0

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: ^4.1.1
  build_runner: ^1.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Akaya
      fonts:
        - asset: fonts/akaya_regular.ttf
